env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  no-console: off
  default-case: off
  max-len: off
  no-plusplus: off
  import/no-unresolved: off
  import/extensions: off
  no-mixed-operators: off
